export const categories = [
  "Sparklers",
  "Flower Pots",
  "Chakram",
  "Bombs",
  "Kuruvi & Lakshmi",
  "Kitkat",
  "Parankivedi&Chorsa",
  "Shots",
  "Outs",
  "Wala",
  // "Ordinary",
];

export const products = [
  //sparkles

  {
    id: "sp-7cm-kb",
    name: "7 cm Crackling",
    price: 85.0,
    category: "Sparklers",
    image: "/images/sparklers/7.jpeg",
    description: "10 packet",
  },
  {
    id: "sp-7cm-cl",
    name: "7 cm Electric",
    price: 95.0,
    category: "Sparklers",
    image: "/images/sparklers/7e.jpeg",
    description: "10 packet",
  },
  {
    id: "sp-10cm-kb",
    name: "10 cm Electric",
    price: 70.0,
    category: "Sparklers",
    image: "/images/sparklers/10e.jpeg",
    description: "5 packet",
  },
  {
    id: "sp-10cm-cl",
    name: "10 cm Colour",
    price: 80.0,
    category: "Sparklers",
    image: "/images/sparklers/10c.jpeg",
    description: "5 packet",
  },
  {
    id: "sp-10cm-gr",
    name: "10 cm Green",
    price: 90.0,
    category: "Sparklers",
    image: "/images/sparklers/10g.jpeg",
    description: "5 packet",
  },
  {
    id: "sp-10cm-rd",
    name: "10 cm Red",
    price: 105.0,
    category: "Sparklers",
    image: "/images/sparklers/10r.jpeg",
    description: "5 packet",
  },
  {
    id: "sp-12cm-kb",
    name: "12 cm Electric",
    price: 130.0,
    category: "Sparklers",
    image: "/images/sparklers/12e.jpeg",
    description: "5 packet",
  },
  {
    id: "sp-12cm-cl",
    name: "12 cm Colour",
    price: 140.0,
    category: "Sparklers",
    image: "/images/sparklers/12c.jpeg",
    description: "5 packet",
  },
  {
    id: "sp-15cm-kb",
    name: "15 cm Electric",
    price: 80.0,
    category: "Sparklers",
    image: "/images/sparklers/15e.jpeg",
    description: "2 packet",
  },
  {
    id: "sp-15cm-cl",
    name: "15 cm Colour",
    price: 90.0,
    category: "Sparklers",
    image: "/images/sparklers/15c.jpeg",
    description: "2 packet",
  },
  {
    id: "sp-50cm-kb",
    name: "50 cm Electric",
    price: 200.0,
    category: "Sparklers",
    image: "/images/sparklers/30e.jpeg",
    description: "1 packet",
  },
  {
    id: "sp-50cm-cl",
    name: "50 cm Colour ",
    price: 230.0,
    category: "Sparklers",
    image: "/images/sparklers/30c.jpeg",
    description: "1 packet",
  },

  // Fountains
  {
    id: "fn-pksm",
    name: "Flower pot small",
    price: 250.0,
    category: "Flower Pots",
    image: "/images/fountains/s1.jpeg",
    description: "5 packet (10 pcs/Packet)",
  },
  {
    id: "fn-pkbg",
    name: "Flower pt Big",
    price: 350.0,
    category: "Flower Pots",
    image: "/images/fountains/b1.jpeg",
    description: "5 packet (10 pcs/Packet)",
  },
  {
    id: "fn-pksp",
    name: "Flower pot Special",
    price: 450.0,
    category: "Flower Pots",
    image: "/images/fountains/sp1.jpeg",
    description: "5 packet (10 pcs/Packet)",
  },
  {
    id: "fn-pkas",
    name: "Flower pot Ashoka",
    price: 240.0,
    category: "Flower Pots",
    image: "/images/fountains/fpasoka.jpeg",
    description: "2 packet (10 pcs/Packet)",
  },
  {
    id: "fn-clkt",
    name: "Flower pot Colourkoti",
    price: 430.0,
    category: "Flower Pots",
    image: "/images/fountains/flowerkoti.jpeg",
    description: "2 packet (10 pcs/Packet)",
  },
  // { id: "fn-dlpk", name: "Deluxe Pookkutti (ഡീലക്സ് പൂക്കുറ്റി)", price: 320.00, category: "Flower Pots", image: "/images/fountains/deluxe-pookkutti.jpg", description: "2 packet (5 pcs/Packet)" },
  //chakram
  {
    id: "fn-nlbg",
    name: "Ground chakkar Big",
    price: 210.0,
    category: "Chakram",
    image: "/images/chakrams/gd-big.jpeg",
    description: "5 packet (10 pcs/Packet)",
  },
  {
    id: "fn-nlsp",
    name: "Ground chakkar Special",
    price: 360.0,
    category: "Chakram",
    image: "/images/chakrams/gd-special.jpeg",
    description: "5 packet (10 pcs/Packet)",
  },
  {
    id: "fn-nldx",
    name: "Ground chakkar Deluxe",
    price: 260.0,
    category: "Chakram",
    image: "/images/chakrams/gd-deluxe.jpeg",
    description: "2 packet (10 pcs/Packet)",
  },
  // { id: "fn-pkso", name: "Pookkutti Special Ordinary (പൂക്കുറ്റി സ്പെഷ്യൽ)", price: 55.00, category: "Chakram", image: "/images/chakrams/pookkutti-special-ordinary.jpg", badge: "Ordinary", description: "1 packet" },
  // { id: "fn-ckso", name: "Chakram Special Ordinary (ചക്രം സ്പെഷ്യൽ)", price: 50.00, category: "Chakram", image: "/images/chakrams/chakram-special-ordinary.jpg", badge: "Ordinary", description: "1 packet" },
  
  //bombs
  {
    id: "fc-hb",
    name: "Hydro Bomb ",
    price: 400.0,
    category: "Bombs",
    image: "/images/bombs/hydro.jpeg",
    description: "5 packet",
  },
  {
    id: "fc-kb",
    name: "King Bomb",
    price: 520.0,
    category: "Bombs",
    image: "/images/bombs/king.jpeg",
    description: "5 packet",
  },
  {
    id: "fc-cb",
    name: "Classic Bomb",
    price: 650.0,
    category: "Bombs",
    image: "/images/bombs/classic.jpeg",
    description: "5 packet",
  },
  // {
  //   id: "fc-ab",
  //   name: "Agni Bomb ",
  //   price: 350.0,
  //   category: "Bombs",
  //   image: "/images/bombs/agni.jpeg",
  //   description: "2 packet",
  // },
  // {
  //   id: "fc-kr",
  //   name: "King Rider [polythene packet] ",
  //   price: 380.0,
  //   category: "Bombs",
  //   image: "/images/bombs/king2.jpeg",
  //   description: "2 packet (Polythene Packet)",
  // },
  {
    id: "rk-1",
    name: "Rocket bomb",
    price: 160.0,
    category: "Bombs",
    image: "/images/bombs/rocketb.jpeg",
    description: "2 packet (10 pcs/Packet)",
  },

  // Kuruvi & Lakshmi
  // {
  //   id: "fc-pv",
  //   name: "Paranki Vedi (പറങ്കിവെടി)",
  //   price: 260.0,
  //   category: "Parankivedi&Chorsa",
  //   image: "/images/kuruvi&lakshmi/paranki-vedi.jpeg",
  //   description: "5 packet (100 Pcs First)",
  // },
   {
    id: "fc-234kv",
    name: "2 3/4 Kuruvi Vedi ",
    price: 280.0,
    category: "Kuruvi & Lakshmi",
    image: "/images/kuruvi&lakshmi/kuruvi.jpeg",
    description: "25 Packet Bundle",
  },
  {
    id: "fc-312lv",
    name: "3 1/2 Lakshmi Vedi",
    price: 200.0,
    category: "Kuruvi & Lakshmi",
    image: "/images/kuruvi&lakshmi/3.5lakshmi.jpeg",
    description: "10 Packet Bundle",
  },
  {
    id: "fc-4il",
    name: "4 Inch Lakshmi",
    price: 300.0,
    category: "Kuruvi & Lakshmi",
    image: "/images/kuruvi&lakshmi/4lakshmi.jpeg",
    description: "10 Packet Bundle",
  },
  {
    id: "fc-5im",
    name: "5 Inch Megalakshmi",
    price: 300.0,
    category: "Kuruvi & Lakshmi",
    image: "/images/kuruvi&lakshmi/5lakshmi.jpeg",
    description: "5 Packet Bundle",
  },
  {
    id: "fc-ds",
    name: "Double Sound ",
    price: 200.0,
    category: "Kuruvi & Lakshmi",
    image: "/images/kuruvi&lakshmi/2sound.jpeg",
    description: "5 Packet Bundle",
  },
  //Wala
  {
    id: "fc-100m",
    name: "100 Wala",
    price: 150.0,
    category: "Wala",
    image: "/images/walas/100.jpeg",
    description: "3 Packet",
  },
  {
    id: "fc-200m",
    name: "200 Wala",
    price: 200.0,
    category: "Wala",
    image: "/images/walas/200.jpeg",
    description: "2 Packet",
  },
  {
    id: "fc-300m",
    name: "300 Wala",
    price: 300.0,
    category: "Wala",
    image: "/images/walas/300.jpeg",
    description: "2 Packet",
  },
  {
    id: "fc-600m",
    name: "600 Wala",
    price: 600.0,
    category: "Wala",
    image: "/images/walas/600.jpeg",
    description: "2 Packet",
  },
  {
    id: "fc-1000m",
    name: "1000 Wala",
    price: 700.0,
    category: "Wala",
    image: "/images/walas/1k.jpeg",
    description: "2 Packet",
  },
  {
    id: "fc-2000m",
    name: "2000 Wala",
    price: 700.0,
    category: "Wala",
    image: "/images/walas/2k.jpeg",
    description: "1 Packet",
  },
  {
    id: "fc-5000m",
    name: "5000 Wala",
    price: 1750.0,
    category: "Wala",
    image: "/images/walas/5k.jpeg",
    description: "1 Packet",
  },
  {
    id: "fc-10000m",
    name: "10000 Wala",
    price: 3500.0,
    category: "Wala",
    image: "/images/walas/10k.jpeg",
    description: "1 Packet",
  },
  //chorsa & parangi
  {
    id: "as-28cso",
    name: "28 chorsa",
    price: 450.0,
    category: "Parankivedi&Chorsa",
    image: "/images/chorsa/28c.jpeg",
    badge: "Ordinary",
    description: "25 packet",
  },
  {
    id: "as-28gso",
    name: "28 Gaint",
    price: 250.0,
    category: "Parankivedi&Chorsa",
    image: "/images/chorsa/28g.jpeg",
    badge: "Ordinary",
    description: "10 packet",
  },
  {
    id: "as-56gso",
    name: "56 Gaint",
    price: 500.0,
    category: "Parankivedi&Chorsa",
    image: "/images/chorsa/56g.jpeg",
    badge: "Ordinary",
    description: "10 packet",
  },
  {
    id: "as-pvso",
    name: "Bijili(100 pcs)",
    price: 260.0,
    category: "Parankivedi&Chorsa",
    image: "/images/chorsa/para.jpeg",
    badge: "Ordinary",
    description: "5 packet",
  },

  // Kitkat
  {
    id: "rc-kk",
    name: "Kitkat",
    price: 140.0,
    category: "Kitkat",
    image: "/images/kitkat/kk.jpeg",
    description: "5 packet (10 pcs/Packet)",
  },
  {
    id: "rc-mkk",
    name: "Mega Kitkat",
    price: 300.0,
    category: "Kitkat",
    image: "/images/kitkat/kkb.jpeg",
    description: "5 packet (10 pcs/Packet)",
  },

  //shots
  {
    id: "as-12so",
    name: "12 Shot",
    price: 380.0,
    category: "Shots",
    image: "/images/shots/12.jpeg",
    badge: "Ordinary",
    description: "2 packet",
  },
  {
    id: "as-30so",
    name: "30 Shot",
    price: 460.0,
    category: "Shots",
    image: "/images/shots/30.jpeg",
    badge: "Ordinary",
    description: "1 packet",
  },
  {
    id: "as-60so",
    name: "60 Shot",
    price: 920.0,
    category: "Shots",
    image: "/images/shots/60.jpeg",
    badge: "Ordinary",
    description: "1 packet",
  },
  {
    id: "as-120so",
    name: "120 Shot",
    price: 1750.0,
    category: "Shots",
    image: "/images/shots/120.jpeg",
    badge: "Ordinary",
    description: "1 packet",
  },

  // { id: "as-240sf", name: "240 Shot First (240 ഷോട്ട് ഫസ്റ്റ്)", price: 3500.00, category: "Shots", image: "/images/aerial-shells/240-shot-first.jpg", description: "1 Packet" },
  // { id: "as-240ss", name: "240 Shot Second (240 ഷോട്ട് സെക്കന്റ്)", price: 3100.00, category: "Shots", image: "/images/aerial-shells/240-shot-second.jpg", description: "1 Packet" },
  //outs
  {
    id: "as-2mco",
    name: "2 inch mix colur out",
    price: 300.0,
    category: "Outs",
    image: "/images/outs/2inch.jpeg",
    description: "1 Packet (3 Ps Pkt)",
  },
  {
    id: "as-25fso",
    name: "2.5 inch out",
    price: 180.0,
    category: "Outs",
    image: "/images/outs/2.5inch.jpeg",
    description: "1 Packet",
  },
  {
    id: "as-3fso",
    name: "3 inch out",
    price: 270.0,
    category: "Outs",
    image: "/images/outs/3inch.jpeg",
    description: "1 Packet",
  },
  {
    id: "as-35fso",
    name: "3.5 inch out",
    price: 300.0,
    category: "Outs",
    image: "/images/outs/3.5inch.jpeg",
    description: "1 Packet",
  },
  {
    id: "as-4fso",
    name: "4 inch single out",
    price: 380.0,
    category: "Outs",
    image: "/images/outs/4inch.jpeg",
    description: "1 Packet",
  },
  {
    id: "as-4fdo",
    name: "4 inch double out",
    price: 580.0,
    category: "Outs",
    image: "/images/outs/4d.jpeg",
    description: "1 Packet",
  },
  // { id: "as-5fso", name: "5\" Fancy Single Oat (5\" ഫാൻസി സിംഗിൾഓട്ട്)", price: 670.00, category: "Shots", image: "/images/aerial-shells/5-fancy-single-oat.jpg", description: "1 Packet" },
];

export function getProductsByCategory(category) {
  return products.filter((p) => p.category === category);
}

export function searchProducts(query, category, minPrice, maxPrice) {
  return products.filter((p) => {
    const matchesQuery = query
      ? p.name.toLowerCase().includes(query.toLowerCase()) ||
        p.category.toLowerCase().includes(query.toLowerCase())
      : true;
    const matchesCategory = category ? p.category === category : true;
    const matchesMinPrice = minPrice !== undefined ? p.price >= minPrice : true;
    const matchesMaxPrice = maxPrice !== undefined ? p.price <= maxPrice : true;
    return (
      matchesQuery && matchesCategory && matchesMinPrice && matchesMaxPrice
    );
  });
}
